<a href="https://colab.research.google.com/github/Ajaysahu01/DATA-ANALYSIS-PROJECTS-ON-PYTHON/blob/main/netflix_watch_time_hours_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
netflix_watch_time = np.random.randint(10,601,1000)
netflix_watch_time

array([134, 318, 123, 430, 565,  24, 515, 187, 328, 370, 274, 318, 425,
       583, 567, 599, 173,  44, 344, 457, 591, 287, 318, 289,  26, 212,
        45, 368, 548, 419, 174, 573, 232, 320,  40, 249, 226, 207, 548,
        87, 434, 152, 315, 537, 126, 191,  48, 163, 512, 395,  53, 407,
       305, 423,  39, 529, 311, 139, 504, 264, 543, 464, 300, 218, 116,
       530, 509, 290,  52, 449, 230, 423, 577, 306, 205, 281, 190, 348,
       571,  67, 209, 171, 378, 184, 192, 281, 385, 105, 175, 391, 306,
       364, 521, 167, 540, 324, 281, 556, 549, 265,  65, 116, 228, 402,
       510, 428,  14, 412, 130, 287,  17, 456, 355, 571, 331, 475, 432,
       378,  88, 277, 531, 441, 287, 105, 485, 117, 427, 502, 117, 338,
       482, 357,  61, 100, 173, 365,  31, 283,  97, 141,  45, 161,  96,
       242,  69, 571, 384, 289, 570, 102, 493, 269, 130, 516, 548,  63,
        84,  58, 269, 324, 546, 253, 495, 500, 458, 250, 234, 236, 399,
       555, 203, 228, 482, 120, 492, 426, 282, 387, 111,  57,  95, 370,
       574, 115, 522, 537, 164, 463, 258,  43, 130, 548, 418, 423,  12,
       229, 441,  68, 184, 562, 104, 560,  74, 495, 155, 110,  90, 145,
       326,  97, 153, 466, 401, 549, 103, 560, 153,  64,  21,  24, 574,
        61, 166, 513,  18, 584, 295, 286, 595, 439, 534, 578, 527, 335,
       519, 205, 456, 299, 470, 262, 502, 461, 473, 223, 144,  64, 222,
       520, 470, 291,  57, 309, 257, 436, 591, 310, 520, 334, 519, 262,
       192, 426, 470, 262,  33, 290, 527, 347, 405,  95, 404, 185, 309,
       326, 435, 449, 344, 190, 146, 573,  23, 107, 280, 469, 177, 326,
       285, 477, 313, 150, 539,  90, 232, 330, 441, 461, 260, 129, 179,
       212, 521, 529, 228, 271, 135,  30, 532, 515,  76, 302,  46,  52,
       474, 138,  82, 279, 240, 586, 396, 591, 588, 562, 221, 474, 422,
        41, 391, 299, 595, 165,  62, 556,  99, 107,  38, 477,  72, 147,
       125, 139, 213, 385, 570, 502, 210, 255, 403, 274, 170, 204, 111,
       472, 207, 277, 450,  78, 173, 321, 284,  23, 122,  51,  42, 376,
       163, 415, 322, 166, 532, 293, 509, 146, 380, 295,  63, 335, 368,
       215, 378, 352, 130,  54, 415, 221, 107, 222, 484, 189, 293, 574,
       140,  26,  65, 149, 302, 285, 466, 329, 567, 389, 292, 165, 297,
       239, 446, 517, 240, 420, 262, 233, 578, 565, 288, 507, 235, 225,
       235, 317,  50, 227, 372,  32, 102, 186, 128, 482, 387, 511, 308,
       133, 154, 121, 280, 296, 290, 459, 458, 243, 561, 516, 415, 244,
       492, 245, 502, 415, 247,  11, 552,  92, 512,  38, 593,  73, 266,
       599, 392,  27, 204,  88, 378, 301, 312, 338, 487,  57, 462,  36,
       341, 220, 565,  84, 226,  16, 330, 146, 439, 377, 478, 465, 474,
       532, 396, 323,  25, 595, 111, 173, 102, 311, 170,  16, 476, 496,
       592, 507, 517, 194, 443, 564, 369,  20, 551, 264, 268,  58, 471,
       138, 391, 596, 216, 178, 438, 493, 353,  74, 553, 184, 465,  82,
       225, 276, 261, 446, 467, 514, 385, 215,  63, 151, 331, 127, 556,
       234,  33,  54,  70, 396, 495, 387, 578, 107, 480, 417, 216, 197,
       583,  28, 585, 419,  67, 455, 464,  89, 311, 600, 291, 242, 586,
       279, 259, 336, 236, 251, 198,  57,  95, 412, 370, 221, 566, 175,
        41, 479, 485,  84,  93, 516, 551, 285, 192, 582, 518, 134, 382,
       566, 124, 316, 223, 394, 176,  90, 385, 107,  18, 365, 375, 567,
        34, 520, 552,  21, 259, 131, 514, 144, 378, 548,  27, 106, 432,
        91,  58, 482, 295, 266, 351, 539, 233, 520, 199,  33,  25, 446,
       132, 126, 557,  61, 178, 149, 566,  46, 322,  28,  17, 101, 553,
       372,  32, 201, 598, 382, 265, 438, 230,  47, 415, 403, 361, 267,
       272, 197, 409, 473, 164, 534,  50, 577, 512, 587, 472, 167,  69,
       173, 478, 146, 306, 415, 174,  46, 538, 387, 265,  50, 388, 452,
       455, 406, 304, 456, 365, 583,  33, 259,  78, 520, 210, 113,  62,
       520, 474, 339, 395, 287, 567, 354, 490, 387, 546, 357, 525, 529,
       197, 515, 129, 126, 299, 516, 377, 180, 312,  75,  75, 479, 159,
       516,  44, 347, 557,  75, 435, 215, 330, 252, 573, 562, 343, 476,
        13, 506, 168, 132, 280, 100, 223, 409, 586, 243, 122, 527, 229,
       398, 542, 402, 465, 302, 431, 378, 406, 479, 532, 418, 487,  80,
       145, 255, 369, 524, 489, 416, 317, 322, 261, 372, 547, 557, 352,
        83, 198, 320, 401, 468, 444, 274, 292, 254, 103, 433, 415, 181,
       447, 339, 269, 572, 108, 255, 162, 209, 109, 407, 358, 572, 399,
       319, 177, 116, 566, 587, 304, 457, 315, 446, 109, 561,  20, 262,
       599, 220, 311, 285, 522, 251, 141, 547, 529, 512, 148,  58, 407,
        47, 459, 287, 556, 559, 221, 306, 482, 215, 314, 457, 548, 326,
       556, 425,  32, 584, 471, 322, 579, 129, 194, 392, 507, 134,  48,
        30,  53, 175, 147, 122, 109, 310, 389, 557, 295,  72, 507, 191,
       118, 254, 575, 102, 494,  29, 100, 336, 363, 256, 355,  67, 100,
       469, 188,  72,  58, 441, 547, 186, 600, 248, 310, 271,  15, 168,
       374, 295, 589, 135, 334,  64, 308,  71,  86, 283, 147,  85, 491,
        59, 494, 160, 539, 373, 544, 345, 267, 239, 461, 523, 166,  94,
        25, 177, 152, 246, 316, 454, 278,  63, 499, 354, 113, 402, 362,
       472, 420, 490, 295, 549, 574, 127, 592, 127, 132, 324, 513, 180,
       355, 501, 353, 305, 464, 424, 567, 344, 398, 291, 393, 378, 186,
       260, 567, 128, 274, 103, 476, 240,  27, 592, 177, 466, 592, 548,
       198, 257, 402,  75, 596, 291,  68, 446, 555, 460, 172, 346, 324,
       438,  94,  93, 389,  75, 153, 514,  71, 196, 535, 344,  84, 312,
        59, 499, 501, 550, 187, 298,  73, 163, 347, 365, 242, 122])

In [ ]:
watch_time = pd.Series(netflix_watch_time, name="watch_time_per_day")
watch_time

0      134
1      318
2      123
3      430
4      565
      ...
995    163
996    347
997    365
998    242
999    122
Name: watch_time_per_day, Length: 1000, dtype: int64

In [ ]:
watch_time.size

1000

In [ ]:
watch_time.shape

(1000,)

In [ ]:
watch_time.ndim

1

In [ ]:
watch_time.index

RangeIndex(start=0, stop=1000, step=1)

In [ ]:
watch_time.isnull().sum()

np.int64(0)

In [ ]:
#total usage time
watch_time.sum()

np.int64(307450)

In [ ]:
#average daily usage
watch_time.mean()

np.float64(307.45)

In [ ]:
#highest usage
watch_time.max()

600

In [ ]:
#lowest
watch_time.min()

11

In [ ]:
#top 10 usage time
watch_time.nlargest(10)

555    600
878    600
15     599
455    599
806    599
640    598
509    596
966    596
228    595
328    595
Name: watch_time_per_day, dtype: int64

In [ ]:
# 10 lowest usage
watch_time.nsmallest(10)

447    11
194    12
728    13
106    14
882    15
473    16
491    16
110    17
634    17
224    18
Name: watch_time_per_day, dtype: int64

In [ ]:
#greater than 300
watch_time[watch_time > 300]

1      318
3      430
4      565
6      515
8      328
      ...
989    499
990    501
991    550
996    347
997    365
Name: watch_time_per_day, Length: 506, dtype: int64

In [ ]:
watch_time[watch_time > 300].count()

np.int64(506)

In [ ]:
#user between 120 and 240
watch_time[(watch_time >= 120) & (watch_time <= 240)]

0      134
2      123
7      187
16     173
25     212
      ...
980    153
983    196
992    187
995    163
999    122
Name: watch_time_per_day, Length: 195, dtype: int64

In [ ]:
watch_time[(watch_time >= 120) & (watch_time <= 240)].count()

np.int64(195)

In [ ]:
#usage less than 60
watch_time[watch_time < 60]

5      24
17     44
24     26
26     45
34     40
       ..
882    15
897    59
910    25
956    27
988    59
Name: watch_time_per_day, Length: 82, dtype: int64

In [ ]:
watch_time[watch_time < 60].count()

np.int64(82)

In [ ]:
#ascending order
watch_time.sort_values()

447     11
194     12
728     13
106     14
882     15
      ...
455    599
806    599
15     599
878    600
555    600
Name: watch_time_per_day, Length: 1000, dtype: int64

In [ ]:
#descending order
watch_time.sort_values(ascending=False)

555    600
878    600
15     599
455    599
806    599
      ...
882     15
106     14
728     13
194     12
447     11
Name: watch_time_per_day, Length: 1000, dtype: int64

In [ ]:
#index of highest user
watch_time.nlargest(1).index

Index([555], dtype='int64')

In [ ]:
#index of lowest usage
watch_time.nsmallest(1).index

Index([447], dtype='int64')

In [ ]:
#user use above average
average = watch_time.mean()
average

np.float64(307.45)

In [ ]:
watch_time[watch_time >average]

1      318
3      430
4      565
6      515
8      328
      ...
989    499
990    501
991    550
996    347
997    365
Name: watch_time_per_day, Length: 494, dtype: int64

In [ ]:
#median
watch_time.median()

304.5

In [ ]:
#convert minutes into hours
watch_time_hours = watch_time / 60
watch_time_hours

0      2.233333
1      5.300000
2      2.050000
3      7.166667
4      9.416667
         ...
995    2.716667
996    5.783333
997    6.083333
998    4.033333
999    2.033333
Name: watch_time_per_day, Length: 1000, dtype: float64

In [ ]:
#total usage time
watch_time_hours.sum()

np.float64(5124.166666666668)

In [ ]:
#more than 5 hours users
watch_time_hours[watch_time_hours > 5]

1      5.300000
3      7.166667
4      9.416667
6      8.583333
8      5.466667
         ...
989    8.316667
990    8.350000
991    9.166667
996    5.783333
997    6.083333
Name: watch_time_per_day, Length: 506, dtype: float64

In [ ]:
#difference between highest and lowest usage
watch_time.max() - watch_time.min()

589

In [ ]:
# reduce users usage time by 10%
watch_time_reduction = watch_time * 0.9
w = watch_time_reduction.sum()
w

np.float64(276705.0)

In [ ]:
# new average after 10% reduction
new_average = watch_time_reduction.mean()
new_average

np.float64(276.705)